In [1]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior.csv')

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Promo Code Used,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,10001,56,Female,Shoes,Footwear,57.19,Oregon,L,Olive,Spring,4.7,No,Standard,No,No,33,PayPal,Annually
1,10002,69,Female,Sweater,Clothing,76.03,California,L,Green,Spring,3.4,No,Standard,No,No,2,PayPal,Bi-Weekly
2,10003,46,Male,Belt,Accessories,77.08,Texas,M,Red,Summer,2.7,No,Free Shipping,Yes,Yes,3,PayPal,Weekly
3,10004,32,Female,Dress,Clothing,55.76,Florida,XL,Blue,Summer,4.4,No,2-Day Shipping,No,No,4,Credit Card,Annually
4,10005,60,Female,Pants,Clothing,45.27,Pennsylvania,L,Maroon,Spring,4.8,Yes,Free Shipping,No,No,9,Debit Card,Quarterly

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             1000 non-null   int64
 1   Age                     1000 non-null   int64
 2   Gender                  1000 non-null   str
 3   Item Purchased          1000 non-null   str
 4   Category                1000 non-null   str
 5   Purchase Amount         1000 non-null   float64
 6   Location                1000 non-null   str
 7   Size                    1000 non-null   str
 8   Color                   1000 non-null   str
 9   Season                  1000 non-null   str
 10  Review Rating           995 non-null    float64
 11  Subscription Status     1000 non-null   str
 12  Shipping Type           1000 non-null   str
 13  Promo Code Used         1000 non-null   str
 14  Discount Applied        1000 non-null   str
 15  Previous Purchases      1000 non-null   int64
 16  Payment Method          1000 non-null   str
 17  Frequency of Purchases  1000 non-null   str
dtypes: float64(2), int64(3), str(13)
memory usage: 213.6 KB

In [4]:
df.describe(include = "all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Promo Code Used,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,1000.000000,1000.000000,1000,1000,1000,1000.000000,1000,1000,1000,1000,995.000000,1000,1000,1000,1000,1000.000000,1000,1000
unique,NaN,NaN,2,20,4,NaN,20,5,16,4,NaN,2,6,2,2,NaN,6,6
top,NaN,NaN,Female,Jeans,Clothing,NaN,Pennsylvania,M,White,Summer,NaN,No,Standard,No,No,NaN,Credit Card,Monthly
freq,NaN,NaN,513,80,513,NaN,68,358,77,255,NaN,638,350,545,545,NaN,260,227
mean,10500.500000,44.385000,NaN,NaN,NaN,64.311340,NaN,NaN,NaN,NaN,3.740000,NaN,NaN,NaN,NaN,24.001000,NaN,NaN
std,288.819436,15.321669,NaN,NaN,NaN,24.739902,NaN,NaN,NaN,NaN,0.764312,NaN,NaN,NaN,NaN,15.177264,NaN,NaN
min,10001.000000,18.000000,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,1.500000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,10250.750000,31.750000,NaN,NaN,NaN,48.482500,NaN,NaN,NaN,NaN,3.200000,NaN,NaN,NaN,NaN,10.000000,NaN,NaN
50%,10500.500000,45.000000,NaN,NaN,NaN,64.960000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,23.500000,NaN,NaN
75%,10750.250000,57.000000,NaN,NaN,NaN,80.605000,NaN,NaN,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,37.000000,NaN,NaN
max,11000.000000,70.000000,NaN,NaN,NaN,145.510000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [5]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount           0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             5
Subscription Status       0
Shipping Type             0
Promo Code Used           0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [6]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount           0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Promo Code Used           0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'promo_code_used', 'discount_applied', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [10]:
# Create a Column age_group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group']= pd.qcut(df['age'], q=4, labels = labels)

In [11]:
df[['age', 'age_group']].head(10)

   age    age_group
0   56  Middle-aged
1   69       Senior
2   46  Middle-aged
3   32        Adult
4   60       Senior
5   25  Young Adult
6   38        Adult
7   56  Middle-aged
8   36        Adult
9   40        Adult

In [12]:
#Create column purchase_frequency_days.

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [13]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(30)

    purchase_frequency_days frequency_of_purchases
0                       365               Annually
1                        14              Bi-Weekly
2                         7                 Weekly
3                       365               Annually
4                        90              Quarterly
5                       365               Annually
6                         7                 Weekly
7                        14              Bi-Weekly
8                         7                 Weekly
9                        30                Monthly
10                       30                Monthly
11                       14            Fortnightly
12                        7                 Weekly
13                       30                Monthly
14                       30                Monthly
15                        7                 Weekly
16                      365               Annually
17                       14              Bi-Weekly
18                       90              Quarterly
19                      365               Annually
20                       30                Monthly
21                       14              Bi-Weekly
22                       14              Bi-Weekly
23                      365               Annually
24                       14              Bi-Weekly
25                       90              Quarterly
26                      365               Annually
27                      365               Annually
28                       30                Monthly
29                       90              Quarterly

In [14]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0               No              No
1               No              No
2              Yes             Yes
3               No              No
4               No              No
5               No              No
6              Yes             Yes
7               No              No
8               No              No
9              Yes             Yes

In [15]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [16]:
df = df.drop('promo_code_used', axis = 1)

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [18]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in C:\Users\user\anaconda3\Lib\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in C:\Users\user\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\Users\user\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\user\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [24]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

connection_url = URL.create(
    "postgresql+psycopg2",
    username="postgres",
    password="Sql@2006",
    host="localhost",
    port=5432,
    database="customer_behavior"
)

engine = create_engine(connection_url)

print("Engine created successfully")

Engine created successfully

In [25]:
table_name = "customer"

df.to_sql(table_name, engine, if_exists="replace", index=False)

print("Data successfully loaded!")

Data successfully loaded!